services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: rubber
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dominos@25
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: "supersecret"
      DEBUG: "1"
<<<<<<< HEAD
=======
      DJANGO_ALLOWED_HOSTS: "backend,backend.rubber-duck.solutions,www.rubber-duck.solutions,rubber-duck.solutions,localhost,127.0.0.1"
>>>>>>> bdfc760 (fixes for docker)
      DB_NAME: rubber
      DB_USER: postgres
      DB_PASSWORD: Dominos@25
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./backend:/app
      - media_data:/app/media
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: "https://backend.rubber-duck.solutions"
      NEXT_PUBLIC_BASE_URL: "https://backend.rubber-duck.solutions"
      NEXT_PUBLIC_API: "https://backend.rubber-duck.solutions"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
  media_data:
