services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: "supersecret"
      DEBUG: "1"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

